In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from pathlib import Path
from sklearn.metrics import confusion_matrix,classification_report
from tensorflow.python.keras import layers
from tensorflow.python.keras.models import Sequential
from tensorflow.python.keras.utils.all_utils import to_categorical
np.set_printoptions(linewidth=150)
img_shape = (32,32,1) # img_shape is 32,32 and 32,32,1 is needed for CNN

In [2]:
def get_images(folder):
    return np.array([plt.imread(file).reshape(img_shape) for file in folder.iterdir()])

def get_labels(folder):
    return np.array([int(file.stem.split('_')[-1]) for file in folder.iterdir()]) - 1

def load_data(path):
    return get_images(path), get_labels(path)

In [3]:
train_folder = Path().cwd() / 'Dataset' / 'train'
test_folder = Path().cwd() / 'Dataset' / 'test'

train_images, train_labels = load_data(train_folder)
test_images, test_labels = load_data(test_folder)

In [4]:
n_class = len(np.unique(train_labels))
train_labels = to_categorical(train_labels, num_classes=n_class)
test_labels = to_categorical(test_labels, num_classes=n_class)

In [5]:
# Define and compile the model
model = Sequential()
model.add(layers.Conv2D(32, (5, 5), input_shape=img_shape, activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Conv2D(64, (5, 5), activation='relu'))
model.add(layers.MaxPooling2D((2, 2)))
model.add(layers.Flatten())
model.add(layers.Dense(1024, activation='relu'))
model.add(layers.Dense(n_class, activation='softmax'))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# Train and evaluate the model
model.fit(train_images, train_labels, epochs=16, batch_size=32)
loss, acc = model.evaluate(test_images, test_labels, batch_size=32)
print('Test loss:', loss)
print('Test accuracy:', acc)


Epoch 1/16
420/420 [==============================] - 23s 45ms/step - loss: 1.1219 - accuracy: 0.6485
Epoch 2/16
420/420 [==============================] - 21s 51ms/step - loss: 0.3744 - accuracy: 0.8753
Epoch 3/16
420/420 [==============================] - 20s 47ms/step - loss: 0.2194 - accuracy: 0.9272
Epoch 4/16
420/420 [==============================] - 19s 46ms/step - loss: 0.1488 - accuracy: 0.9499
Epoch 5/16
420/420 [==============================] - 20s 47ms/step - loss: 0.0997 - accuracy: 0.9657
Epoch 6/16
420/420 [==============================] - 22s 52ms/step - loss: 0.0751 - accuracy: 0.9747
Epoch 7/16
420/420 [==============================] - 19s 45ms/step - loss: 0.0542 - accuracy: 0.9815
Epoch 8/16
420/420 [==============================] - 20s 49ms/step - loss: 0.0553 - accuracy: 0.9815
Epoch 9/16
420/420 [==============================] - 22s 53ms/step - loss: 0.0474 - accuracy: 0.9833
Epoch 10/16
420/420 [==============================] - 22s 54ms/step - loss: 0.040

In [6]:
# Make predictions on the test data
predictions = model.predict(test_images)
# Convert the predictions and test labels to one-hot encoded form
arabic_characters = np.array(['أ', 'ب', 'ت', 'ث', 'ج', 'ح', 'خ', 'د', 'ذ', 'ر', 'ز', 'س', 'ش', 'ص', 'ض', 'ط', 'ظ', 'ع', 'غ', 'ف', 'ق', 'ك', 'ل', 'م', 'ن', 'ه', 'و', 'ي'])
predictions = arabic_characters[np.argmax(predictions, axis=1)]
y_test = arabic_characters[np.argmax(test_labels, axis=1)]

print(confusion_matrix(y_test, predictions))

[[120   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 117   1   0   0   0   0   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0]
 [  0   0 116   0   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   2   0   0   0   0   0   1   0]
 [  0   0  10 106   0   0   0   1   1   0   0   0   0   0   0   0   0   2   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 114   2   0   0   0   0   0   0   1   0   0   0   0   0   0   0   1   0   0   0   0   0   2   0]
 [  0   0   0   0   2 115   1   0   0   0   0   0   0   0   0   0   0   2   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   7 106   0   0   0   0   0   0   0   0   0   0   5   2   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   1   1   0 111   5   1   1   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   6 110   0   3   0   0   0   0   0   0   0   0   

In [7]:
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           أ       0.98      1.00      0.99       120
           ب       0.95      0.97      0.96       120
           ت       0.82      0.97      0.89       120
           ث       0.96      0.88      0.92       120
           ج       0.95      0.95      0.95       120
           ح       0.88      0.96      0.92       120
           خ       0.90      0.88      0.89       120
           د       0.87      0.93      0.90       120
           ذ       0.84      0.92      0.88       120
           ر       0.85      0.93      0.89       120
           ز       0.91      0.82      0.86       120
           س       0.98      0.93      0.95       120
           ش       0.97      0.95      0.96       120
           ص       0.93      0.97      0.95       120
           ض       0.99      0.85      0.91       120
           ط       0.93      0.93      0.93       120
           ظ       0.95      0.88      0.91       120
           ع       0.88    